name: 'Test Deploy Ansible Playbook'
description: |
  Provisions an OpenStack compute instance, runs a user-defined Ansible Playbook
  against the instance, collects artifacts, and cleans up resources afterwards.

inputs:
  osAuthUrl:
    description: 'URL pointing to OpenStack authentication API'
    required: true

  osRegionName:
    description: 'OpenStack region name. Example: RegionOne'
    required: true

  osApplicationCredentialId:
    description: 'OpenStack application credential ID'
    required: true

  osApplicationCredentialSecret:
    description: 'OpenStack application credential secret'
    required: true

  osExternalNetworkName:
    description: 'Name of the external OpenStack network for floating IPs'
    required: true

  osPrivateNetworkName:
    description: 'Name of the private OpenStack network name to attach the test compute instance to'
    required: true

  osSecurityGroupName:
    description: 'Name of the OpenStack security group assigned to the test compute instance'
    required: true

  osKeypairName:
    description: 'Name of the pre-uploaded public ssh keypair in OpenStack'
    required: true

  osFlavorName:
    description: 'Name the OpenStack flavor to use for the instance'
    required: true

  osImageName:
    description: 'Name of the image to use for the OpenStack compute instance'
    required: true

  instanceNamePrefix:
    description: 'Prefix for the OpenStack compute instance (will prepend to the GitHub run id)'
    required: false
    default: 'github'

  pythonVersion:
    description: 'Python version to be used during testing'
    required: false
    default: '3.10.19'

  ansibleVersion:
    description: 'Ansible version to be used during testing (must be supported by the specified Python version)'
    required: false
    default: '10.7.0'

  ansibleUser:
    description: 'Operative system user which Ansible impersonates when connecting to the test compute instance'
    required: true

  ansibleSshPrivateKey:
    description: 'Value of the private ssh keypair for compute instance access'
    required: true

  pathToMainFile:
    description: 'Path to main file for the Ansible Playbook execution. Example: site.yml'
    required: true

  pathToRequirementsFile:
    description: 'Path to requirements file needed for the Ansible Playbook. Example: requirements.yml'
    required: false

  inputSpecJson:
    description: 'Input values for the Ansible Playbook, in JSON format'
    required: false

outputs:
  artifactPath:
    description: 'Path where artifacts were written in the workflow workspace'
    value: ${{ steps.test-deploy-ansible-playbook.outputs.artifactPath }}

runs:
  using: 'composite'
  steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1
          terraform_wrapper: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.pythonVersion }}

      - name: Setup Ansible
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir python-openstackclient ansible==${{ inputs.ansibleVersion }}
        shell: bash

      - name: Set GitHub Path
        run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        shell: bash
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}

      - name: Test Deploy Ansible Playbook
        id: test-deploy-ansible-playbook
        run: test-deploy-ansible-playbook.sh
        shell: bash
        env:
          TF_IN_AUTOMATION: true
          OS_AUTH_URL: ${{ inputs.osAuthUrl }}
          OS_REGION_NAME: ${{ inputs.osRegionName }}
          OS_APPLICATION_CREDENTIAL_ID: ${{ inputs.osApplicationCredentialId }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ inputs.osApplicationCredentialSecret }}
          ANSIBLE_SSH_PRIVATE_KEY: ${{ inputs.ansibleSshPrivateKey }}
          OS_EXTERNAL_NETWORK_NAME: ${{ inputs.osExternalNetworkName }}
          OS_PRIVATE_NETWORK_NAME: ${{ inputs.osPrivateNetworkName }}
          OS_SECURITY_GROUP_NAME: ${{ inputs.osSecurityGroupName }}
          OS_FLAVOR_NAME: ${{ inputs.osFlavorName }}
          OS_IMAGE_NAME: ${{ inputs.osImageName }}
          OS_KEYPAIR_NAME: ${{ inputs.osKeypairName }}
          ANSIBLE_USER: ${{ inputs.ansibleUser }}
          INSTANCE_NAME_PREFIX: ${{ inputs.instanceNamePrefix }}
          PATH_TO_MAIN_FILE: ${{ inputs.pathToMainFile }}
          PATH_TO_REQUIREMENTS_FILE: ${{ inputs.pathToRequirementsFile }}
          INPUT_SPEC_JSON: ${{ inputs.inputSpecJson }}
