name: 'Test Deploy Ansible Playbook'
description: |
  Provisions an OpenStack compute instance, runs a user-defined Ansible Playbook
  against the instance, collects artifacts, and cleans up resources afterwards.

inputs:
  os-auth-url:
    description: 'URL pointing to OpenStack authentication API'
    required: true

  os-region-name:
    description: 'OpenStack region name. Example: RegionOne'
    required: true

  os-application-credential-id:
    description: 'OpenStack application credential ID'
    required: true

  os-application-credential-secret:
    description: 'OpenStack application credential secret'
    required: true

  os-external-network-name:
    description: 'Name of the external OpenStack network for floating IPs'
    required: true

  os-private-network-name:
    description: 'Name of the private OpenStack network name to attach the test compute instance to'
    required: true

  os-security-group-name:
    description: 'Name of the OpenStack security group assgined to the test compute instance'
    required: true

  os-keypair-name:
    description: 'Name of the pre-uploaded public ssh keypair in OpenStack'
    required: true

  os-flavor-name:
    description: 'Name the OpenStack flavor to use for the instance'
    required: true

  os-image-name:
    description: 'Name of the image to use for the OpenStack compute instance'
    required: true

  instance-name-prefix:
    description: 'Prefix for the OpenStack compute instance (will prepend to the GitHub run id)'
    required: false
    default: 'github'

  ansible-user:
    description: 'Operative system user which Ansible impersonates when connecting to the test compute intance'
    required: true

  ansible-ssh-private-key:
    description: 'Value of the private ssh keypair for compute instance access'
    required: true

  path-to-main-file:
    description: 'Path to main file for the Ansible Playbook execution. Example: site.yml'
    required: true

  path-to-requirements-file:
    description: 'Path to requirements file needed for the Ansible Playbook. Example: requirements.yml'
    required: false
    default: ''

  input-spec-json:
    description: 'Input values for the Ansible Playbook, in JSON format'
    required: false
    default: '{}'

outputs:
  artifact_path:
    description: 'Path where artifacts were written in the workflow workspace'

runs:
  using: 'composite'
  steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.1
          terraform_wrapper: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.19

      - name: Setup Ansible
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir python-openstackclient ansible==10.7.0
        shell: bash

      - name: Set GitHub Path
        run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        shell: bash
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}

      - name: Test Deploy Ansible Playbook
        id: test-deploy-ansible-playbook
        run: entrypoint.sh
        shell: bash
        env:
          TF_IN_AUTOMATION: true
          OS_AUTH_URL: ${{ inputs.os-auth-url }}
          OS_REGION_NAME: ${{ inputs.os-region-name }}
          OS_APPLICATION_CREDENTIAL_ID: ${{ inputs.os-application-credential-id }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ inputs.os-application-credential-secret }}
          ANSIBLE_SSH_PRIVATE_KEY: ${{ inputs.ansible-ssh-private-key }}
          OS_EXTERNAL_NETWORK_NAME: ${{ inputs.os-external-network-name }}
          OS_PRIVATE_NETWORK_NAME: ${{ inputs.os-private-network-name }}
          OS_SECURITY_GROUP_NAME: ${{ inputs.os-security-group-name }}
          OS_FLAVOR_NAME: ${{ inputs.os-flavor-name }}
          OS_IMAGE_NAME: ${{ inputs.os-image-name }}
          OS_KEYPAIR_NAME: ${{ inputs.os-keypair-name }}
          ANSIBLE_USER: ${{ inputs.ansible-user }}
          INSTANCE_NAME_PREFIX: ${{ inputs.instance-name-prefix }}
          PATH_TO_MAIN_FILE: ${{ inputs.path-to-main-file }}
          PATH_TO_REQUIREMENTS_FILE: ${{ inputs.path-to-requirements-file }}
          INPUT_SPEC_JSON: ${{ inputs.input-spec-json }}
